config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :galleries do
    resources :photos, controller: 'galleries/photos' do
      resources :comments, controller: 'galleries/photos/comments'
    end
  end

  resources :tags do
    get '/assign_to_gallery/:gallery_id', to: 'tags#assign_to_gallery', as: :assign_to_gallery
    get '/assign_to_photo/:photo_id', to: 'tags#assign_to_photo', as: :assign_to_photo
  end

  root to: 'galleries#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :photo
  validates :username, presence: true
  validates :comment, presence: true
end

app/models/gallery.rb
class Gallery < ApplicationRecord
  validates :name, presence: true, uniqueness: true
  validates :description, presence: true
  has_many :photos, inverse_of: :gallery, dependent: :destroy
  has_many :gallery_tags, dependent: :destroy
  has_many :galleries, through: :gallery_tags, dependent: :destroy
  accepts_nested_attributes_for :photos

end

app/models/gallery_tag.rb
class GalleryTag < ApplicationRecord
  belongs_to :gallery
  belongs_to :tag
end

app/models/photo.rb
class Photo < ApplicationRecord
  has_one_attached :image
  validates :name, presence: true, uniqueness: true
  belongs_to :gallery
  has_many :comments, inverse_of: :photo, dependent: :destroy
  has_many :photo_tags, dependent: :destroy
  has_many :photos, through: :photo_tags, dependent: :destroy
  accepts_nested_attributes_for :comments

  # def image_on_disk
  #   ActiveStorage::Blob.service.path_for(image.key)
  # end
  # validates :photo_path,
  #           content_type: { in: /\Aimage\/.*\z/, message: 'must be an image' },
  #           size: { less_than: 4.megabytes , message: 'must be less than 4 MB' }
end

app/models/photo_tag.rb
class PhotoTag < ApplicationRecord
  belongs_to :photo
  belongs_to :tag
end

app/models/tag.rb
class Tag < ApplicationRecord
  validates :name, presence: true, uniqueness: true

  has_many :photo_tags, dependent: :destroy
  has_many :photos, through: :photo_tags

  has_many :gallery_tags, dependent: :destroy
  has_many :galleries, through: :gallery_tags
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/galleries/photos/comments_controller.rb
class Galleries::Photos::CommentsController < ApplicationController
  def new
    @gallery = Gallery.find params[:gallery_id]
    @photo = Photo.find params[:photo_id]
    @comment = @photo.comments.build
  end
  
  def create
    @gallery = Gallery.find params[:gallery_id]
    @photo = Photo.find params[:photo_id]
    @comment = Comment.new(comment_params)
    @comment.photo = @photo
    @comment.save
    redirect_to gallery_photo_path(@gallery, @photo)
  end

  private 

  def comment_params
    params.require(:comment).permit(
      :username,
      :comment
    )
  end
end

app/controllers/galleries/photos_controller.rb
class Galleries::PhotosController < ApplicationController
  
  def new 
    @gallery = Gallery.find params[:gallery_id]
    @photo = @gallery.photos.build
  end

  def create
    @gallery = Gallery.find params[:gallery_id]
    @photo = Photo.new(photo_params)

    @photo.gallery = @gallery
    if @photo.valid?
      @photo.save
      redirect_to gallery_path(@gallery)
    else
      flash[:error] = "Error occurred, please fix the error and try again"
      render "new"
    end
  end

  def edit
    @photo = Photo.find params[:id]
    @gallery = @photo.gallery
  end

  def update
    @photo = Photo.find params[:id]
    @gallery = @photo.gallery
    @photo.assign_attributes(photo_params)

    if @photo.valid?
      @photo.save!
      redirect_to gallery_path(@gallery)
    else
      flash[:error] = "Error occurred, please fix the error and try again"
      render "edit"
    end
  end

  def show
    @gallery = Gallery.find params[:gallery_id]
    @photo = Photo.find params[:id]
    @photo_tags = PhotoTag.where(photo: @photo)
    @tags = Tag.all
  end

  def destroy
    photo = Photo.find params[:id]
    gallery = photo.gallery

    photo.destroy
    redirect_to gallery_path(gallery)
  end

  private

  def photo_params
    params.require(:photo).permit(
      :name,
      :shooting_date,
      :description,
      :image
    )
  end
end

app/controllers/galleries_controller.rb
class GalleriesController < ApplicationController
  def index
    page = params[:page] || 1
    page_size = 10
    @q = Gallery.ransack(params[:q])
    @galleries = @q.result.page(page).per(page_size)

  end
  
  def new
    @gallery = Gallery.new
  end

  def create
    @gallery = Gallery.new(gallery_params)

    if @gallery.valid?
      @gallery.save
      redirect_to galleries_path
    else
      flash[:error] = "Error occurred, please fix the error and try again"
      render "new"
    end
  end

  def show
    @gallery = Gallery.find params[:id]
    page = params[:page] || 1
    page_size = 10
    @q = @gallery.photos.ransack(params[:q])
    @photos = @q.result.page(page).per(page_size)
    @gallery_tags = GalleryTag.where(gallery: @gallery)
    @tags = Tag.all
  end

  def edit
    @gallery = Gallery.find params[:id]
  end

  def update
    @gallery = Gallery.find params[:id]
    @gallery.assign_attributes(gallery_params)

    if @gallery.valid?
      @gallery.save!
      redirect_to galleries_path
    else
      flash[:error] = "Error occurred, please fix the error and try again"
      render "edit"
    end
  end

  def destroy
    @gallery = Gallery.find params[:id]
    @gallery.destroy
    redirect_to galleries_path
  end

  private

  def gallery_params
    params.require(:gallery).permit(
      :name,
      :description
    )
  end

end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  def index
    page = params[:page] || 1
    page_size = 10
    @tags = Tag.all.page(page).per(page_size)
  end

  def show
    @tag = Tag.find params[:id]
    @gallery_tags = GalleryTag.where(tag: @tag)
    @photo_tags = PhotoTag.where(tag: @tag)
  end

  def new
    @tag = Tag.new
  end

  def create
    @tag = Tag.new(tag_params)

    if @tag.valid?
      @tag.save
      redirect_to tags_path
    else
      flash[:error] = "Error occurred, please fix the error and try again"
      render "new"
    end
  end

  def edit
    @tag = Tag.find params[:id]
  end

  def update
    @tag = Tag.find params[:id]
    @tag.assign_attributes(tag_params)    

    if @tag.valid?
      @tag.save!
    else
      flash[:error] = "Error occurred, please fix the error and try again"
      render "edit"
    end
  end

  def destroy
    tag = Tag.find params[:id]
    tag.destroy
    redirect_to tags_path
  end

  def assign_to_gallery
    gallery = Gallery.find params[:gallery_id]
    tag = Tag.find params[:tag_id]
    
    if GalleryTag.where(gallery: gallery, tag: tag).exists?
      flash[:error] = "Tag already assigned to this gallery"
    else
      gallery_tag = GalleryTag.create(gallery: gallery, tag: tag)
    end
    redirect_back(fallback_location: galleries_path)
  end

  def assign_to_photo
    photo = Photo.find params[:photo_id]
    tag = Tag.find params[:tag_id]

    if PhotoTag.where(photo: photo, tag: tag).exists?
      flash[:error] = "Photo already assigned to this gallery"
    else
      photo_tag = PhotoTag.create(photo: photo, tag: tag)
    end
    redirect_back(fallback_location: galleries_path)
  end

  private

  def tag_params
    params.require(:tag).permit(
      :name
    )
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/date_helper.rb
module DateHelper
  def format_date(date)
    date.strftime("%Y-%m-%d %-l:%M %p %Z")
  end
end

app/helpers/galleries/photos/comments_helper.rb
module Galleries::Photos::CommentsHelper
end

app/helpers/galleries/photos_helper.rb
module Galleries::PhotosHelper
end

app/views/galleries/edit.html.erb
Edit Gallery form

<%= form_with(url: gallery_path(@gallery), model: @gallery, method: "patch") do |form| %>
  <%= form.text_field :name %>
  <%= form.text_area :description %>
  <br>
  <%= form.submit %>
<% end %>

app/views/galleries/index.html.erb
<h2> Galleries </h2>

<div class="row">
  <div class="col-md-12">
    <%= link_to 'New Gallery', new_gallery_path, class: 'btn btn-primary' %>

    <%= link_to 'Tags', tags_path, class: 'ms-3 btn btn-info' %>
  </div>
</div>

<h5> Search Galleries </h5>
<%= search_form_for @q do |f| %>
  <%= f.label :name_cont %>
  <%= f.search_field :name_cont %>

  <%= f.label :description_cont %>
  <%= f.search_field :description_cont %>

  <%= f.submit 'Search', class: 'btn btn-primary' %>
  <%= link_to 'Clear Filter', galleries_path, class: 'btn btn-secondary' %>    
<% end %>


<table class="table table-striped">
	<thead>
		<tr>
			<th>Gallery Name</th>
			<th>Gallery Description</th>
    </tr>
  </thead>
  <tbody>
    <% @galleries.each do |gallery| %>
      <tr>
        <td> <%= link_to gallery.name, gallery_path(gallery) %> </td>

        <td> <%= gallery.description %> </td>
      </tr>
    <% end %>
  </tbody>
</table>

<div class="row">
  <div class="col-12 col-md-9">
    <%= paginate @galleries %>
  </div>
  <div class="col-12 col-md-3">
    <%= page_entries_info @galleries %>
  </div>
</div>

app/views/galleries/new.html.erb
<h2> New Gallery form </h2>

<%= form_with model: @gallery do |form| %>
  <div class="row">
    <div class="col-md-3">
      <%= form.label :name, class: 'control-label fw-bold required' %>
    </div>
    <div class="col-md-7">
      <%= form.text_field :name, class: 'form-control' %>
    </div>
  </div>

    <div class="row mt-3">
      <div class="col-md-3">
        <%= form.label :description, class: 'control-label fw-bold required' %>
      </div>
      <div class="col-md-7">
        <%= form.text_area :description, class: 'form-control' %>
      </div>
    </div>

  <div class="row mt-2">
    <div class="col-md-12">
      <%= form.submit 'Create New Gallery', class: 'btn btn-primary' %>
    </div>
  </div>
<% end %>

app/views/galleries/photos/_form.html.erb
<div class="row mt-3">
  <div class="col-md-3">
    <%= form.label :name, class: 'control-label fw-bold required' %>
  </div>
  <div class="col-md-7">
    <%= form.text_field :name, class: 'form-control' %>
  </div>
  </div>

  <div class="row mt-3">
  <div class="col-md-3">
    <%= form.label :image, class: 'control-label fw-bold required' %>
  </div>
  <div class="col-md-7">
    <%= form.file_field :image, class: 'form-control' %>
  </div>
  </div>

  <div class="row mt-3">
  <div class="col-md-3">
    <%= form.label :description, class: 'control-label fw-bold required' %>
  </div>
  <div class="col-md-7">
    <%= form.text_area :description, class: 'form-control' %>
  </div>
  </div>

  <div class="row mt-3">
  <div class="col-md-3">
    <%= form.label :shooting_date, class: 'control-label fw-bold required' %>
  </div>
  <div class="col-md-7">
    <%= form.date_field :shooting_date, class: 'form-control' %>
  </div>
</div>

app/views/galleries/photos/comments/new.html.erb
<h2> New Comment </h2>

<%= form_with(model: @comment, url: gallery_photo_comments_path(@gallery, @photo)) do |form| %>
  <div class="row mt-3">
    <div class="col-md-3">
      <%= form.label :username, class: 'control-label fw-bold required' %>
    </div>
    <div class="col-md-7">
      <%= form.text_field :username, class: 'form-control' %>
    </div>
  </div>

  <div class="row mt-3">
    <div class="col-md-3">
      <%= form.label :comment, class: 'control-label fw-bold required' %>
    </div>
    <div class="col-md-7">
      <%= form.text_field :comment, class: 'form-control' %>
    </div>
  </div>

  <div class="row mt-2">
    <div class="col-md-12">
      <%= form.submit 'Create New Comment', class: 'btn btn-primary' %>
    </div>
  </div>

  <%= link_to 'Back', gallery_photo_path(@gallery, @photo) %>

<% end %>

app/views/galleries/photos/edit.html.erb
<h2> Edit Photo <%= @photo.name %> </h2>

<% if flash[:error] %>
  <div class="alert alert-danger" role="alert">
    <%= flash[:error] %>
  </div>
<% end %>

<%= form_with(model: @photo, url: gallery_photo_path(@gallery, @photo), method: "patch") do |form| %>

  <%= render partial: 'form', locals: {form: form} %>
  <div class="row mt-2">
    <div class="col-md-12">
      <%= form.submit 'Update Photo', class: 'btn btn-primary' %>
    </div>
  </div>
<% end %>

app/views/galleries/photos/new.html.erb
<h2> New Photo Upload </h2>

<%= form_with(model: @photo, url: gallery_photos_path(@gallery)) do |form| %>

  <div class="row mt-3">
    <div class="col-md-3">
      <%= form.label :name, class: 'control-label fw-bold required' %>
    </div>
    <div class="col-md-7">
      <%= form.text_field :name, class: 'form-control' %>
    </div>
  </div>

  <div class="row mt-3">
    <div class="col-md-3">
      <%= form.label :image, class: 'control-label fw-bold required' %>
    </div>
    <div class="col-md-7">
      <%= form.file_field :image, class: 'form-control' %>
    </div>
  </div>

  <div class="row mt-3">
    <div class="col-md-3">
      <%= form.label :description, class: 'control-label fw-bold required' %>
    </div>
    <div class="col-md-7">
      <%= form.text_area :description, class: 'form-control' %>
    </div>
  </div>

  <div class="row mt-3">
    <div class="col-md-3">
      <%= form.label :shooting_date, class: 'control-label fw-bold required' %>
    </div>
    <div class="col-md-7">
      <%= form.date_field :shooting_date, class: 'form-control' %>
    </div>
  </div>

  <div class="row mt-2">
    <div class="col-md-12">
      <%= form.submit 'Create New Photo', class: 'btn btn-primary' %>
    </div>
  </div>
<% end %>

app/views/galleries/photos/show.html.erb
<h2>
  <%= @photo.name %>
</h2>

<% if flash[:error] %>
  <div class="alert alert-danger" role="alert">
    <%= flash[:error] %>
  </div>
<% end %>

<div class="row">
  <div class="col-12">
    <dl>
      <div class="row">
        <dt class="col-md-2 fw-bold">
          Photo Name:
        </dt>
        <dd class="col-md-9">
          <%= @photo.name %>
        </dd>
      </div>

      <div class="row">
        <dt class="col-md-2 fw-bold">
          Photo Description:
        </dt>
        <dd class="col-md-9">
          <%= @photo.description %>
        </dd>
      </div>
      <div class="row">
        <dt class="col-md-2">
          Created At:
        </dt>
        <dd class="col-md-8">
          <%= format_date(@photo.created_at) %>
        </dd>
      </div>
      <div class="row">
        Assigned Tags:
        <div class="col-12">
          <% @photo_tags.each do |pt| %>
            <%= link_to pt.tag.name, tag_path(pt.tag), class: "badge bg-primary"  %>
          <% end %>
        </div>
      </div>

      <div class="row mt-3">
        <div class="col-12">
          <%= link_to "edit #{@photo.name}", edit_gallery_photo_path(@gallery, @photo), class: "btn btn-primary" %>

          <%= form_tag  gallery_photo_path(@gallery, @photo), method: :delete do %>
            <%= button_tag "Delete #{@photo.name}", class: 'btn btn-danger mt-2 mb-2' %>
          <% end %>
          
        </div>
      </div>
    </dl>
  </div>
</div>


<div class="row">
  <div class="col-12">
    <%= image_tag @photo.image.variant(resize: "900x900") %>

    <div class="col-3 col-md-12">
      <h4> Click on tag to assign to photo </h4>
      <% @tags.each do |tag| %>
        <span class="badge bg-info">
          <%= link_to tag.name, tag_assign_to_photo_path(tag, @photo) %>
        </span>
      <% end %>
    </div>
  </div>

  <div class="col-12">
    <%= link_to 'Add new Comment', new_gallery_photo_comment_path(@gallery, @photo), class: 'mt-3 btn btn-success'  %>
    <h3>Comments</h3>
    
    
    <% @photo.comments.each do |comment| %>
    
      <h6> Commented By: <%= comment.username %> </h6>
      <p>
        <%= comment.comment %>
      </p>
    
      <%= format_date(comment.created_at) %>
    
      <hr>
    <% end %>
  </div>
</div>




<%= link_to 'Back to Gallery', gallery_path(@gallery) %>

app/views/galleries/show.html.erb
<h2>
  <%= @gallery.name %>
</h2>

<% if flash[:error] %>
  <div class="alert alert-danger" role="alert">
    <%= flash[:error] %>
  </div>
<% end %>

<div class="row">
  <div class="col-12">
    <dl>
      <div class="row">
        <dt class="col-md-2 fw-bold">
          Gallery Name:
        </dt>
        <dd class="col-md-9">
          <%= @gallery.name %>
        </dd>
      </div>

      <div class="row">
        <dt class="col-md-2 fw-bold">
          Gallery Description:
        </dt>
        <dd class="col-md-9">
          <%= @gallery.description %>
        </dd>
      </div>
      <div class="row">
        <dt class="col-md-2">
          Created At:
        </dt>
        <dd class="col-md-8">
          <%= format_date(@gallery.created_at) %>
        </dd>
      </div>
      <div class="row">
        Assigned Tags:
        <div class="col-12">
          <% @gallery_tags.each do |gt| %>
            <%= link_to gt.tag.name, tag_path(gt.tag), class: "badge bg-primary"  %>
          <% end %>
        </div>
      </div>
    </dl>
  </div>
</div>

<%= link_to "edit #{@gallery.name}", edit_gallery_path(@gallery), class: "btn btn-primary" %>


<%= form_tag  gallery_path(@gallery), method: :delete do %>
  <%= button_tag "Delete #{@gallery.name}", class: 'btn btn-danger mt-2 mb-2' %>
<% end %>


<%= link_to 'upload new photo', new_gallery_photo_path(@gallery), class: 'btn btn-success' %>


<h3 class="mt-3"> Gallery Pictures </h3>

<h5> Search Photos </h5>
<%= search_form_for @q, url: gallery_path(@gallery) do |f| %>
  <%= f.label :name_cont %>
  <%= f.search_field :name_cont %>

  <%= f.label :description_cont %>
  <%= f.search_field :description_cont %>

  <%= f.submit 'Search', class: 'btn btn-primary' %>
  <%= link_to 'Clear Filter', galleries_path, class: 'btn btn-secondary' %>    
<% end %>

<div class="row">
  <div class="col-9 col-md-12">
    <div class="row">
      <% @photos.each do |photo| %>
        <div class="col-4">
          <div class="card" style="width: 18rem;">
            <%= image_tag photo.image.variant(resize: "300x300"), class: "card-img-top" %>
            <div class="card-body">
              <h5 class="card-title">
                <%= link_to photo.name, gallery_photo_path(@gallery, photo) %>
              </h5>
              <p class="card-text"><%= photo.description %></p>
              <%= link_to 'More Details', gallery_photo_path(@gallery, photo), class: "btn btn-primary" %>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>
  <div class="col-3 col-md-12">
    <h4> Click on tag to assign to gallery </h4>
    <% @tags.each do |tag| %>
      <span class="badge bg-info">
        <%= link_to tag.name, tag_assign_to_gallery_path(tag, @gallery) %>
      </span>
    <% end %>
  </div>
</div>

<div class="row mt-3">
  <div class="col-12 col-md-9">
    <%= paginate @photos %>
  </div>
  <div class="col-12 col-md-3">
    <%= page_entries_info @photos %>
  </div>
</div>

<%= link_to 'Back to galleries', root_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Photo Gallery Application</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

  </head>

  <body>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/tags/index.html.erb
<h2> Tags </h2>

<div class="row">
  <div class="col-md-12">
    <%= link_to 'New Tag', new_tag_path, class: 'btn btn-primary' %>
  </div>
</div>


<table class="table table-striped">
	<thead>
		<tr>
			<th>Tag Name</th>
    </tr>
  </thead>
  <tbody>
    <% @tags.each do |tag| %>
      <tr>
        <td> <%= link_to tag.name, tag_path(tag) %> </td>
      </tr>
    <% end %>
  </tbody>
</table>

<div class="row">
  <div class="col-12 col-md-9">
    <%= paginate @tags %>
  </div>
  <div class="col-12 col-md-3">
    <%= page_entries_info @tags %>
  </div>
</div>

<%= link_to 'Home page', root_path %>

app/views/tags/new.html.erb
<h2> New Tag form </h2>

<%= form_with model: @tag do |form| %>
  <div class="row">
    <div class="col-md-3">
      <%= form.label :name, class: 'control-label fw-bold required' %>
    </div>
    <div class="col-md-7">
      <%= form.text_field :name, class: 'form-control' %>
    </div>
  </div>

  <div class="row mt-2">
    <div class="col-md-12">
      <%= form.submit 'Create New Tag', class: 'btn btn-primary' %>
    </div>
  </div>
<% end %>

app/views/tags/show.html.erb
<h3 class="mt-3">Pictures with the tag</h3>

<div class="row">
  <div class="col-9 col-md-12">
    <div class="row">
      <% @photo_tags.each do |pt| %>
        <div class="col-4">
          <div class="card" style="width: 18rem;">
            <%= image_tag pt.photo.image.variant(resize: "300x300"), class: "card-img-top" %>
            <div class="card-body">
              <h5 class="card-title">
                <%= link_to pt.photo.name, gallery_photo_path(pt.photo.gallery, pt.photo) %>
              </h5>
              <p class="card-text"><%= pt.photo.description %></p>
              <%= link_to 'More Details', gallery_photo_path(pt.photo.gallery, pt.photo), class: "btn btn-primary" %>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>


<h3 class="mt-3">Galleries with the tag</h3>

<table class="table table-striped">
	<thead>
		<tr>
			<th>Gallery Name</th>
			<th>Gallery Description</th>
    </tr>
  </thead>
  <tbody>
    <% @gallery_tags.each do |gt| %>
      <tr>
        <td> <%= link_to gt.gallery.name, gallery_path(gt.gallery) %> </td>

        <td> <%= gt.gallery.description %> </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= form_tag tag_path(@tag), method: :delete do %>
  <%= button_tag 'Delete Tag', class: 'btn btn-danger' %>
<% end %>


<%= link_to 'Back to Tags', tags_path %>